name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - ipywidgets=8.0.4
  - ipykernel=6.19.2
  - matplotlib=3.7.1
  - ipython=8.12.0
  - python=3.8.17
  - numpy=1.24.3
  - scipy=1.10.1
  - ipympl=0.9.3
  - ipytone=0.5.1
  - librosa=0.10.0
